import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Footer from "../components/Footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://use.typekit.net/dlv0xph.css" />
			</head>

			<body className={`antialiased overflow-x-hidden w-[100vw]`}>
				<div className="overflow-x-hidden">{children}</div>
			</body>
			<Footer />
		</html>
	);
}
